name: workflow
on:
  pull_request:
    types: [ opened, synchronize, reopened ]
    paths:
      - hoge/*

jobs:
  comment-on-pull-request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 100
          ref: ${{ github.head_ref }}
      - id: diff-check
        if: github.event.action == 'synchronize'
        run: echo "diff-count=$(git diff ${{ github.event.before }} ${{ github.event.after }} --name-only --relative=hoge | wc -l)" >> $GITHUB_OUTPUT
      - id: no-diff-check
        if: github.event.action != 'synchronize'
        run: echo "diff-count=1" >> $GITHUB_OUTPUT
      - uses: actions/github-script@v6
        if: steps.diff-check.outputs.diff-count > 0 || steps.no-diff-check.outputs.diff-count > 0
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `hoge ディレクトリ配下のファイルが編集されました。`
            })
